In [223]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [224]:
cars = pd.read_csv("./car.csv")

In [225]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117927 entries, 0 to 117926
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype 
---  ------           --------------   ----- 
 0   Unnamed: 0       117927 non-null  int64 
 1   mark             117927 non-null  object
 2   model            117927 non-null  object
 3   generation_name  87842 non-null   object
 4   year             117927 non-null  int64 
 5   mileage          117927 non-null  int64 
 6   vol_engine       117927 non-null  int64 
 7   fuel             117927 non-null  object
 8   city             117927 non-null  object
 9   province         117927 non-null  object
 10  price            117927 non-null  int64 
dtypes: int64(5), object(6)
memory usage: 9.9+ MB


In [226]:
cars.isnull().sum()

Unnamed: 0             0
mark                   0
model                  0
generation_name    30085
year                   0
mileage                0
vol_engine             0
fuel                   0
city                   0
province               0
price                  0
dtype: int64

In [227]:
cars.drop(columns=['generation_name'], axis=1, inplace=True)

In [228]:
cars.head()

Unnamed: 0  mark  model  year  mileage  vol_engine    fuel  \
0           0  opel  combo  2015   139568        1248  Diesel   
1           1  opel  combo  2018    31991        1499  Diesel   
2           2  opel  combo  2015   278437        1598  Diesel   
3           3  opel  combo  2016    47600        1248  Diesel   
4           4  opel  combo  2014   103000        1400     CNG   

              city     province  price  
0            Janki  Mazowieckie  35900  
1         Katowice      Śląskie  78501  
2            Brzeg     Opolskie  27000  
3        Korfantów     Opolskie  30800  
4  Tarnowskie Góry      Śląskie  35900

In [229]:
cars = cars.dropna()

In [230]:
fuel_dict = {}
for index, item in enumerate(pd.get_dummies(cars['fuel']).columns) :
    fuel_dict[item] = index

print(fuel_dict)

{'CNG': 0, 'Diesel': 1, 'Electric': 2, 'Gasoline': 3, 'Hybrid': 4, 'LPG': 5}


In [231]:
cars['fuel'].replace(fuel_dict, inplace=True)

In [232]:
cars.head()

Unnamed: 0  mark  model  year  mileage  vol_engine  fuel             city  \
0           0  opel  combo  2015   139568        1248     1            Janki   
1           1  opel  combo  2018    31991        1499     1         Katowice   
2           2  opel  combo  2015   278437        1598     1            Brzeg   
3           3  opel  combo  2016    47600        1248     1        Korfantów   
4           4  opel  combo  2014   103000        1400     0  Tarnowskie Góry   

      province  price  
0  Mazowieckie  35900  
1      Śląskie  78501  
2     Opolskie  27000  
3     Opolskie  30800  
4      Śląskie  35900

Column Selection

In [233]:
# milieage
# vol_engine
# price
# fuel

In [234]:
working_df = cars[['mileage','price','vol_engine']]

In [235]:
X = np.array(working_df[['mileage','vol_engine']])

In [236]:
y = np.array(working_df['price'])

In [237]:
X_train, x_test, y_train, y_test = train_test_split(X,y, test_size=0.3)

In [238]:
X_train

array([[ 64000,   1591],
       [     1,   1199],
       [109290,   1198],
       ...,
       [ 72300,   4395],
       [     5,   1998],
       [225000,   1984]])

In [239]:
y_train

array([ 72900, 129900,  17900, ..., 259000, 320700,  12500])

In [240]:
model = LinearRegression()

In [241]:
model.fit(X_train, y_train)

LinearRegression()

In [251]:
predicted = model.predict(x_test)

In [243]:
model.coef_

array([-0.57668945, 56.32677785])

In [244]:
model.intercept_

49332.19475875115

In [245]:
x1 = np.array(working_df['mileage'])
x2 = np.array(working_df['vol_engine'])

In [246]:
y = model.coef_[0]*x1 + model.coef_[1]*x2 + model.intercept_

In [247]:
y

array([ 39140.62032955, 115317.16255516, -21229.29468379, ...,
       112086.05125413,  59895.65601024,  51233.7804681 ])

In [257]:
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'n_features_in_': 2,
 'coef_': array([-0.57668945, 56.32677785]),
 'rank_': 2,
 'singular_': array([26594135.63794484,   182037.92229834]),
 'intercept_': 49332.19475875115}