In [2]:
import pandas as pd
import numpy as np

In [3]:
cars = pd.read_csv("./car.csv")

In [4]:
cars.isnull().sum()

Unnamed: 0             0
mark                   0
model                  0
generation_name    30085
year                   0
mileage                0
vol_engine             0
fuel                   0
city                   0
province               0
price                  0
dtype: int64

In [5]:
cars.drop(columns=['generation_name'], inplace=True)

In [6]:
cars.head()

Unnamed: 0  mark  model  year  mileage  vol_engine    fuel  \
0           0  opel  combo  2015   139568        1248  Diesel   
1           1  opel  combo  2018    31991        1499  Diesel   
2           2  opel  combo  2015   278437        1598  Diesel   
3           3  opel  combo  2016    47600        1248  Diesel   
4           4  opel  combo  2014   103000        1400     CNG   

              city     province  price  
0            Janki  Mazowieckie  35900  
1         Katowice      Śląskie  78501  
2            Brzeg     Opolskie  27000  
3        Korfantów     Opolskie  30800  
4  Tarnowskie Góry      Śląskie  35900

In [7]:
pd.get_dummies(cars['mark']).columns

Index(['alfa-romeo', 'audi', 'bmw', 'chevrolet', 'citroen', 'fiat', 'ford',
       'honda', 'hyundai', 'kia', 'mazda', 'mercedes-benz', 'mini',
       'mitsubishi', 'nissan', 'opel', 'peugeot', 'renault', 'seat', 'skoda',
       'toyota', 'volkswagen', 'volvo'],
      dtype='object')

In [8]:
def obj_to_numeric(col : pd.Series):
    return_dict = {}
    column = pd.get_dummies(col).columns

    for index, key in enumerate(column):
        return_dict[key] = index
    print(return_dict)
    return return_dict

In [9]:
cars['mark'].replace(obj_to_numeric(cars['mark']), inplace=True)

{'alfa-romeo': 0, 'audi': 1, 'bmw': 2, 'chevrolet': 3, 'citroen': 4, 'fiat': 5, 'ford': 6, 'honda': 7, 'hyundai': 8, 'kia': 9, 'mazda': 10, 'mercedes-benz': 11, 'mini': 12, 'mitsubishi': 13, 'nissan': 14, 'opel': 15, 'peugeot': 16, 'renault': 17, 'seat': 18, 'skoda': 19, 'toyota': 20, 'volkswagen': 21, 'volvo': 22}


In [10]:
cars['fuel'].replace(obj_to_numeric(cars['fuel']), inplace=True)

{'CNG': 0, 'Diesel': 1, 'Electric': 2, 'Gasoline': 3, 'Hybrid': 4, 'LPG': 5}


In [11]:
cars['city'].replace(obj_to_numeric(cars['city']), inplace=True)

{'()': 0, 'Adamowizna': 1, 'Adamowo': 2, 'Adamusy': 3, 'Adamów': 4, 'Adamówka': 5, 'Albigowa': 6, 'Aleksandria': 7, 'Aleksandrowice': 8, 'Aleksandrów': 9, 'Aleksandrów Duży': 10, 'Aleksandrów Kujawski': 11, 'Aleksandrów Pierwszy': 12, 'Aleksandrów Łódzki': 13, 'Altanka': 14, 'Alwernia': 15, 'Andrespol': 16, 'Andrychów': 17, 'Andrzejów Duranowski': 18, 'Anielew': 19, 'Ankamaty': 20, 'Annopol': 21, 'Anonin': 22, 'Antoniew': 23, 'Antoniów': 24, 'Antoniówka': 25, 'Antonów': 26, 'Augustowo': 27, 'Augustów': 28, 'Augustówek': 29, 'Babiak': 30, 'Babica': 31, 'Babice': 32, 'Babice Nowe': 33, 'Babicha': 34, 'Babiec Piaseczny': 35, 'Babienica': 36, 'Babimost': 37, 'Babin': 38, 'Baborów': 39, 'Baboszewo': 40, 'Bachowice': 41, 'Bachórz': 42, 'Baciki Dalsze': 43, 'Baczków': 44, 'Bajerze': 45, 'Bakałarzewo': 46, 'Balice': 47, 'Baligród': 48, 'Banachy': 49, 'Bandrów Narodowy': 50, 'Banie': 51, 'Banie Mazurskie': 52, 'Banino': 53, 'Baniocha': 54, 'Baranowo': 55, 'Baranów': 56, 'Baranówka': 57, 'Barbar

In [12]:
cars['model'].replace(obj_to_numeric(cars['model']), inplace=True)

{'147': 0, '159': 1, '2': 2, '2008': 3, '206': 4, '207': 5, '208': 6, '3': 7, '3008': 8, '307': 9, '308': 10, '3gt': 11, '407': 12, '5': 13, '500': 14, '5008': 15, '500l': 16, '500x': 17, '508': 18, '5gt': 19, '6': 20, '80': 21, 'a-klasa': 22, 'a1': 23, 'a2': 24, 'a3': 25, 'a4': 26, 'a4-allroad': 27, 'a5': 28, 'a6': 29, 'a6-allroad': 30, 'a7': 31, 'a8': 32, 'accord': 33, 'adam': 34, 'agila': 35, 'alhambra': 36, 'almera': 37, 'altea': 38, 'altea-xl': 39, 'amarok': 40, 'amg-gt': 41, 'ampera': 42, 'antara': 43, 'arkana': 44, 'arona': 45, 'arteon': 46, 'astra': 47, 'asx': 48, 'ateca': 49, 'auris': 50, 'avensis': 51, 'aveo': 52, 'aygo': 53, 'b-klasa': 54, 'b-max': 55, 'beetle': 56, 'berlingo': 57, 'bravo': 58, 'c-hr': 59, 'c-klasa': 60, 'c-max': 61, 'c3-aircross': 62, 'c3-picasso': 63, 'c30': 64, 'c4-cactus': 65, 'c4-grand-picasso': 66, 'c4-picasso': 67, 'c5': 68, 'c5-aircross': 69, 'caddy': 70, 'california': 71, 'camaro': 72, 'camry': 73, 'captur': 74, 'caravelle': 75, 'carens': 76, 'cc': 

In [13]:
cars['province'].replace(obj_to_numeric(cars['province']), inplace=True)

{'(': 0, 'Berlin': 1, 'Dolnośląskie': 2, 'Kujawsko-pomorskie': 3, 'Lubelskie': 4, 'Lubuskie': 5, 'Mazowieckie': 6, 'Małopolskie': 7, 'Moravian-Silesian Region': 8, 'Niedersachsen': 9, 'Nordrhein-Westfalen': 10, 'Opolskie': 11, 'Podkarpackie': 12, 'Podlaskie': 13, 'Pomorskie': 14, 'Trenczyn': 15, 'Warmińsko-mazurskie': 16, 'Wiedeń': 17, 'Wielkopolskie': 18, 'Zachodniopomorskie': 19, 'Łódzkie': 20, 'Śląskie': 21, 'Świętokrzyskie': 22}


In [14]:
cars.head()

Unnamed: 0  mark  model  year  mileage  vol_engine  fuel  city  province  \
0           0    15     89  2015   139568        1248     1  1161         6   
1           1    15     89  2018    31991        1499     1  1365        21   
2           2    15     89  2015   278437        1598     1   300        11   
3           3    15     89  2016    47600        1248     1  1510        11   
4           4    15     89  2014   103000        1400     0  3606        21   

   price  
0  35900  
1  78501  
2  27000  
3  30800  
4  35900

Making for Training and Testing

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X = np.array(cars[cars.columns[1:len(cars.columns)-1]])

In [17]:
y = np.array(cars['price'])

In [18]:
X_train, x_test, y_train, y_test = train_test_split(X,y, test_size=0.3)

In [19]:
X_train

array([[   9,  267, 2013, ...,    1,  650,   20],
       [  15,   43, 2007, ...,    1, 2043,   12],
       [   2,  253, 2009, ...,    3, 4422,   11],
       ...,
       [   1,   25, 2002, ...,    1, 4230,   20],
       [  21,  209, 2018, ...,    1,  367,    3],
       [  17,  118, 2009, ...,    1, 2775,    6]])

Model training

1. Multiple Linear Regression

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
mlr = LinearRegression()

In [22]:
mlr.fit(X_train, y_train)

LinearRegression()

In [34]:
X_train[0]

array([     9,    267,   2013, 189000,   1685,      1,    650,     20])

In [23]:
y_test

array([32900, 13400, 23900, ..., 48000, 21900, 39900])

In [24]:
predicted = mlr.predict(x_test)

In [25]:
predicted

array([45907.14685801,  2428.10867955, 42118.52441453, ...,
       94727.67104689, 10526.7300267 , 65809.39857462])

2. DecisionTreeRegressor

In [26]:
from sklearn.tree import DecisionTreeRegressor

In [27]:
dtr = DecisionTreeRegressor()

In [28]:
dtr.fit(X_train, y_train)

DecisionTreeRegressor()

In [29]:
y_test

array([32900, 13400, 23900, ..., 48000, 21900, 39900])

In [30]:
dtr.predict(x_test)

array([26900., 13500., 25900., ..., 49500., 15375., 45000.])

In [31]:
import pickle

In [32]:
pickle.dump(mlr, open("mlr.pkl", "wb"))

In [33]:
pickle.dump(dtr, open("dtr.pkl", "wb"))